import { execSync } from "node:child_process";
import { readdirSync, mkdirSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const IMG_DIR = join(ROOT, "public", "images");
const ILL_DIR = join(ROOT, "public", "illustrations");
const VARIANTS_DIR = join(IMG_DIR, "variants");

const WIDTHS = [480, 768, 1080, 1600];
const WEBP_QUALITY = 82;
const AVIF_QUALITY = 55;

function identify(file) {
  const out = execSync(`identify -format "%w %h" "${file}"`, { encoding: "utf8" }).trim();
  const [w, h] = out.split(" ").map(Number);
  return { w, h };
}

function run(cmd) {
  execSync(cmd, { stdio: "ignore" });
}

function optimizePhotos() {
  if (existsSync(VARIANTS_DIR)) rmSync(VARIANTS_DIR, { recursive: true, force: true });
  mkdirSync(VARIANTS_DIR, { recursive: true });

  const files = readdirSync(IMG_DIR).filter((f) => f.endsWith(".webp"));
  const manifest = {};

  for (const file of files) {
    const base = file.replace(/\.webp$/, "");
    const src = join(IMG_DIR, file);
    const { w, h } = identify(src);

    // Re-compress the original to a sane baseline (served as preload/fallback).
    run(`convert "${src}" -quality ${WEBP_QUALITY} "${src}"`);

    const widths = WIDTHS.filter((x) => x <= w);
    if (widths[widths.length - 1] < w) widths.push(w);
    if (widths[widths.length - 1] > WIDTHS[WIDTHS.length - 1]) {
      widths[widths.length - 1] = Math.min(w, 2000);
    }

    const webp = [];
    const avif = [];

    for (const width of widths) {
      const wPath = join(VARIANTS_DIR, `${base}-${width}.webp`);
      run(`convert "${src}" -resize ${width} -quality ${WEBP_QUALITY} "${wPath}"`);
      webp.push({ w: width, src: `/images/variants/${base}-${width}.webp` });

      const aPath = join(VARIANTS_DIR, `${base}-${width}.avif`);
      run(`convert "${src}" -resize ${width} -quality ${AVIF_QUALITY} "${aPath}"`);
      avif.push({ w: width, src: `/images/variants/${base}-${width}.avif` });
    }

    // Low-quality image placeholder for blur-up.
    const lqipPath = join(VARIANTS_DIR, `${base}-lqip.webp`);
    run(`convert "${src}" -resize 40 -blur 0x3 -quality 35 "${lqipPath}"`);

    manifest[base] = {
      width: w,
      height: h,
      lqip: `/images/variants/${base}-lqip.webp`,
      webp,
      avif,
    };
  }

  return manifest;
}

function convertIllustrations() {
  if (!existsSync(ILL_DIR)) return [];
  const pngs = readdirSync(ILL_DIR).filter((f) => f.toLowerCase().endsWith(".png"));
  const converted = [];
  for (const png of pngs) {
    const src = join(ILL_DIR, png);
    const webpPath = join(ILL_DIR, png.replace(/\.png$/i, ".webp"));
    run(`convert "${src}" -quality 85 "${webpPath}"`);
    rmSync(src);
    converted.push({ from: png, to: png.replace(/\.png$/i, ".webp") });
  }
  return converted;
}

function writeManifest(manifest) {
  const ts = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.\n` +
    `export interface ImageVariant { w: number; src: string; }\n` +
    `export interface ImageManifestEntry {\n  width: number;\n  height: number;\n  lqip: string;\n  webp: ImageVariant[];\n  avif: ImageVariant[];\n}\n` +
    `export const imageManifest: Record<string, ImageManifestEntry> = ${JSON.stringify(manifest, null, 2)};\n`;
  mkdirSync(join(ROOT, "src", "lib"), { recursive: true });
  writeFileSync(join(ROOT, "src", "lib", "imageManifest.ts"), ts);
}

const manifest = optimizePhotos();
const illustrations = convertIllustrations();
writeManifest(manifest);

console.log(`Optimized ${Object.keys(manifest).length} photos.`);
console.log(`Converted ${illustrations.length} illustrations to WebP.`);
