// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export interface ImageVariant { w: number; src: string; }
export interface ImageManifestEntry {
  width: number;
  height: number;
  lqip: string;
  webp: ImageVariant[];
  avif: ImageVariant[];
}
export const imageManifest: Record<string, ImageManifestEntry> = {
  "about_hostel": {
    "width": 751,
    "height": 1333,
    "lqip": "/images/variants/about_hostel-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/about_hostel-480.webp"
      },
      {
        "w": 751,
        "src": "/images/variants/about_hostel-751.webp"
      }
    ],
    "avif": []
  },
  "about_hostel2": {
    "width": 889,
    "height": 1333,
    "lqip": "/images/variants/about_hostel2-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/about_hostel2-480.webp"
      },
      {
        "w": 768,
        "src": "/images/variants/about_hostel2-768.webp"
      },
      {
        "w": 889,
        "src": "/images/variants/about_hostel2-889.webp"
      }
    ],
    "avif": []
  },
  "about_hostel3": {
    "width": 750,
    "height": 1333,
    "lqip": "/images/variants/about_hostel3-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/about_hostel3-480.webp"
      },
      {
        "w": 750,
        "src": "/images/variants/about_hostel3-750.webp"
      }
    ],
    "avif": []
  },
  "dorm2": {
    "width": 2080,
    "height": 1387,
    "lqip": "/images/variants/dorm2-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/dorm2-480.webp"
      },
      {
        "w": 768,
        "src": "/images/variants/dorm2-768.webp"
      },
      {
        "w": 1080,
        "src": "/images/variants/dorm2-1080.webp"
      },
      {
        "w": 1600,
        "src": "/images/variants/dorm2-1600.webp"
      },
      {
        "w": 2000,
        "src": "/images/variants/dorm2-2000.webp"
      }
    ],
    "avif": []
  },
  "dorm3": {
    "width": 1728,
    "height": 2592,
    "lqip": "/images/variants/dorm3-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/dorm3-480.webp"
      },
      {
        "w": 768,
        "src": "/images/variants/dorm3-768.webp"
      },
      {
        "w": 1080,
        "src": "/images/variants/dorm3-1080.webp"
      },
      {
        "w": 1600,
        "src": "/images/variants/dorm3-1600.webp"
      },
      {
        "w": 1728,
        "src": "/images/variants/dorm3-1728.webp"
      }
    ],
    "avif": []
  },
  "dorm4": {
    "width": 3064,
    "height": 5143,
    "lqip": "/images/variants/dorm4-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/dorm4-480.webp"
      },
      {
        "w": 768,
        "src": "/images/variants/dorm4-768.webp"
      },
      {
        "w": 1080,
        "src": "/images/variants/dorm4-1080.webp"
      },
      {
        "w": 1600,
        "src": "/images/variants/dorm4-1600.webp"
      },
      {
        "w": 2000,
        "src": "/images/variants/dorm4-2000.webp"
      }
    ],
    "avif": []
  },
  "dorm_room": {
    "width": 1557,
    "height": 2336,
    "lqip": "/images/variants/dorm_room-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/dorm_room-480.webp"
      },
      {
        "w": 768,
        "src": "/images/variants/dorm_room-768.webp"
      },
      {
        "w": 1080,
        "src": "/images/variants/dorm_room-1080.webp"
      },
      {
        "w": 1557,
        "src": "/images/variants/dorm_room-1557.webp"
      }
    ],
    "avif": []
  },
  "graffiti1": {
    "width": 3000,
    "height": 2000,
    "lqip": "/images/variants/graffiti1-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/graffiti1-480.webp"
      },
      {
        "w": 768,
        "src": "/images/variants/graffiti1-768.webp"
      },
      {
        "w": 1080,
        "src": "/images/variants/graffiti1-1080.webp"
      },
      {
        "w": 1600,
        "src": "/images/variants/graffiti1-1600.webp"
      },
      {
        "w": 2000,
        "src": "/images/variants/graffiti1-2000.webp"
      }
    ],
    "avif": []
  },
  "graffiti2": {
    "width": 2000,
    "height": 3000,
    "lqip": "/images/variants/graffiti2-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/graffiti2-480.webp"
      },
      {
        "w": 768,
        "src": "/images/variants/graffiti2-768.webp"
      },
      {
        "w": 1080,
        "src": "/images/variants/graffiti2-1080.webp"
      },
      {
        "w": 1600,
        "src": "/images/variants/graffiti2-1600.webp"
      },
      {
        "w": 2000,
        "src": "/images/variants/graffiti2-2000.webp"
      }
    ],
    "avif": []
  },
  "graffiti3": {
    "width": 1333,
    "height": 2005,
    "lqip": "/images/variants/graffiti3-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/graffiti3-480.webp"
      },
      {
        "w": 768,
        "src": "/images/variants/graffiti3-768.webp"
      },
      {
        "w": 1080,
        "src": "/images/variants/graffiti3-1080.webp"
      },
      {
        "w": 1333,
        "src": "/images/variants/graffiti3-1333.webp"
      }
    ],
    "avif": []
  },
  "graffiti4": {
    "width": 1976,
    "height": 2963,
    "lqip": "/images/variants/graffiti4-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/graffiti4-480.webp"
      },
      {
        "w": 768,
        "src": "/images/variants/graffiti4-768.webp"
      },
      {
        "w": 1080,
        "src": "/images/variants/graffiti4-1080.webp"
      },
      {
        "w": 1600,
        "src": "/images/variants/graffiti4-1600.webp"
      },
      {
        "w": 1976,
        "src": "/images/variants/graffiti4-1976.webp"
      }
    ],
    "avif": []
  },
  "home_hero": {
    "width": 1008,
    "height": 1344,
    "lqip": "/images/variants/home_hero-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/home_hero-480.webp"
      },
      {
        "w": 768,
        "src": "/images/variants/home_hero-768.webp"
      },
      {
        "w": 1008,
        "src": "/images/variants/home_hero-1008.webp"
      }
    ],
    "avif": []
  },
  "home_sweet_home": {
    "width": 806,
    "height": 1216,
    "lqip": "/images/variants/home_sweet_home-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/home_sweet_home-480.webp"
      },
      {
        "w": 768,
        "src": "/images/variants/home_sweet_home-768.webp"
      },
      {
        "w": 806,
        "src": "/images/variants/home_sweet_home-806.webp"
      }
    ],
    "avif": []
  },
  "hostel_illustration1": {
    "width": 1424,
    "height": 949,
    "lqip": "/images/variants/hostel_illustration1-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/hostel_illustration1-480.webp"
      },
      {
        "w": 768,
        "src": "/images/variants/hostel_illustration1-768.webp"
      },
      {
        "w": 1080,
        "src": "/images/variants/hostel_illustration1-1080.webp"
      },
      {
        "w": 1424,
        "src": "/images/variants/hostel_illustration1-1424.webp"
      }
    ],
    "avif": []
  },
  "hostel_illustration2": {
    "width": 2000,
    "height": 1333,
    "lqip": "/images/variants/hostel_illustration2-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/hostel_illustration2-480.webp"
      },
      {
        "w": 768,
        "src": "/images/variants/hostel_illustration2-768.webp"
      },
      {
        "w": 1080,
        "src": "/images/variants/hostel_illustration2-1080.webp"
      },
      {
        "w": 1600,
        "src": "/images/variants/hostel_illustration2-1600.webp"
      },
      {
        "w": 2000,
        "src": "/images/variants/hostel_illustration2-2000.webp"
      }
    ],
    "avif": []
  },
  "how_it_works1": {
    "width": 1040,
    "height": 1560,
    "lqip": "/images/variants/how_it_works1-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/how_it_works1-480.webp"
      },
      {
        "w": 768,
        "src": "/images/variants/how_it_works1-768.webp"
      },
      {
        "w": 1040,
        "src": "/images/variants/how_it_works1-1040.webp"
      }
    ],
    "avif": []
  },
  "how_it_works2": {
    "width": 2000,
    "height": 1333,
    "lqip": "/images/variants/how_it_works2-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/how_it_works2-480.webp"
      },
      {
        "w": 768,
        "src": "/images/variants/how_it_works2-768.webp"
      },
      {
        "w": 1080,
        "src": "/images/variants/how_it_works2-1080.webp"
      },
      {
        "w": 1600,
        "src": "/images/variants/how_it_works2-1600.webp"
      },
      {
        "w": 2000,
        "src": "/images/variants/how_it_works2-2000.webp"
      }
    ],
    "avif": []
  },
  "welcome_hostel": {
    "width": 898,
    "height": 1200,
    "lqip": "/images/variants/welcome_hostel-lqip.webp",
    "webp": [
      {
        "w": 480,
        "src": "/images/variants/welcome_hostel-480.webp"
      },
      {
        "w": 768,
        "src": "/images/variants/welcome_hostel-768.webp"
      },
      {
        "w": 898,
        "src": "/images/variants/welcome_hostel-898.webp"
      }
    ],
    "avif": []
  },
  "hostel_bedroom_isometric": {
    "width": 1200,
    "height": 960,
    "lqip": "/images/variants/hostel_bedroom_isometric-lqip.webp",
    "webp": [
      { "w": 480, "src": "/images/variants/hostel_bedroom_isometric-480.webp" },
      { "w": 768, "src": "/images/variants/hostel_bedroom_isometric-768.webp" },
      { "w": 1080, "src": "/images/variants/hostel_bedroom_isometric-1080.webp" },
      { "w": 1200, "src": "/images/variants/hostel_bedroom_isometric-1200.webp" }
    ],
    "avif": [
      { "w": 480, "src": "/images/variants/hostel_bedroom_isometric-480.avif" },
      { "w": 768, "src": "/images/variants/hostel_bedroom_isometric-768.avif" },
      { "w": 1080, "src": "/images/variants/hostel_bedroom_isometric-1080.avif" },
      { "w": 1200, "src": "/images/variants/hostel_bedroom_isometric-1200.avif" }
    ]
  }
};
